### ISSUE TITLE
When does an obligation become 'Fulfilled'

### ISSUE THREAD

**Issue by JimTurnerAtStirling** [hmrc/vat-obligations#20]
Can anyone clarify at what point a Vat Obligation gets a status of Fulfilled?  Is this immediately on submission of the Vat Return or at some other time?

Thanks.

**Comment by davidmthornton** [comment]
From our BA: A Return Obligation will receive a Fulfilled status as soon as the post request has been sent to ETMP. There are the edge cases when the APIs are not available for the post and get, which would mean the status would not be updated straight away.

**Comment by JimTurnerAtStirling** [comment]
Thanks
